// Generates src/theme/tokens.ts from the web's src/styles/tokens.css — the one place the design tokens live
// (CLAUDE.md; docs/05 "After M8: branding" changes tokens.css only). React Native has no CSS variables and no oklch(),
// so the semantic colours are resolved through their var() chain and converted to hex, spacing and radius to numbers.
// `pnpm --filter @gymos/mobile tokens` rewrites the file; a unit test fails when it is out of date.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
export const CSS_PATH = join(here, "../../web/src/styles/tokens.css");
export const OUT_PATH = join(here, "../src/theme/tokens.ts");

const SEMANTIC = ["background", "foreground", "card", "card-foreground", "primary", "primary-foreground", "secondary", "secondary-foreground",
  "muted", "muted-foreground", "accent", "accent-foreground", "destructive", "destructive-foreground", "border", "input", "ring",
  "success", "success-foreground", "warning", "warning-foreground", "info", "info-foreground"];

function block(css, selector) {
  const i = css.indexOf(`${selector} {`);
  if (i < 0) return {};
  let depth = 0, j = i;
  for (; j < css.length; j++) { if (css[j] === "{") depth++; else if (css[j] === "}" && --depth === 0) break; }
  const vars = {};
  for (const m of css.slice(i, j).replace(/\/\*[\s\S]*?\*\//g, "").matchAll(/--([\w-]+)\s*:\s*([^;]+);/g)) vars[m[1]] = m[2].trim();
  return vars;
}

function oklchToHex(l, c, h) {
  const hr = (h * Math.PI) / 180;
  const a = c * Math.cos(hr), b = c * Math.sin(hr);
  const l_ = l + 0.3963377774 * a + 0.2158037573 * b, m_ = l - 0.1055613458 * a - 0.0638541728 * b, s_ = l - 0.0894841775 * a - 1.291485548 * b;
  const [L, M, S] = [l_ ** 3, m_ ** 3, s_ ** 3];
  const lin = [4.0767416621 * L - 3.3077115913 * M + 0.2309699292 * S, -1.2684380046 * L + 2.6097574011 * M - 0.3413193965 * S, -0.0041960863 * L - 0.7034186147 * M + 1.707614701 * S];
  const gamma = (x) => (x <= 0.0031308 ? 12.92 * x : 1.055 * x ** (1 / 2.4) - 0.055);
  return "#" + lin.map((x) => Math.round(Math.min(1, Math.max(0, gamma(x))) * 255).toString(16).padStart(2, "0")).join("");
}

function color(value, vars, seen = new Set()) {
  const ref = value.match(/^var\(--([\w-]+)\)$/);
  if (ref) {
    if (seen.has(ref[1])) throw new Error(`token cycle at --${ref[1]}`);
    return color(vars[ref[1]], vars, new Set([...seen, ref[1]]));
  }
  const ok = value.match(/^oklch\(\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)\s*(?:\/\s*([\d.]+)(%?))?\s*\)$/);
  if (ok) {
    const hex = oklchToHex(Number(ok[1]), Number(ok[2]), Number(ok[3]));
    if (ok[4] === undefined) return hex;
    const alpha = ok[5] === "%" ? Number(ok[4]) / 100 : Number(ok[4]);
    return hex + Math.round(alpha * 255).toString(16).padStart(2, "0");
  }
  if (/^#[0-9a-f]{3,8}$/i.test(value)) return value.toLowerCase();
  throw new Error(`unsupported colour value: ${value}`);
}

const camel = (k) => k.replace(/-(\w)/g, (_, c) => c.toUpperCase());

export function generate(css = readFileSync(CSS_PATH, "utf8")) {
  const light = block(css, ":root");
  const dark = { ...light, ...block(css, ".dark") };
  const colors = (vars) => Object.fromEntries(SEMANTIC.map((k) => [camel(k), color(vars[k], vars)]));
  const series = (vars) => Array.from({ length: 8 }, (_, i) => vars[`series-${i + 1}`]).filter(Boolean).map((v) => color(v, vars));
  const rem = (v) => Number(v.replace("rem", "")) * 16;
  const unit = rem(light["space-unit"]);
  const radius = rem(light["radius"]);
  const tokens = {
    light: { ...colors(light), series: series(light) },
    dark: { ...colors(dark), series: series(dark) },
    space: { 1: unit, 2: unit * 2, 3: unit * 3, 4: unit * 4, 6: unit * 6, 8: unit * 8, 12: unit * 12 },
    radius: { sm: radius - 4, md: radius - 2, lg: radius, xl: radius + 4, full: 9999 },
    tap: 48,
  };
  return `// GENERATED by apps/mobile/scripts/tokens.mjs from apps/web/src/styles/tokens.css — do not edit; run \`pnpm --filter @gymos/mobile tokens\`.\n` +
    `export const tokens = ${JSON.stringify(tokens, null, 2)} as const;\n\nexport type ColorName = keyof typeof tokens.light;\n`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(OUT_PATH, generate());
  console.log(`wrote ${OUT_PATH}`);
}
