// GENERATED by apps/mobile/scripts/tokens.mjs from apps/web/src/styles/tokens.css — do not edit; run `pnpm --filter @gymos/mobile tokens`.
export const tokens = {
  "light": {
    "background": "#ffffff",
    "foreground": "#0a0a0a",
    "card": "#ffffff",
    "cardForeground": "#0a0a0a",
    "primary": "#171717",
    "primaryForeground": "#fafafa",
    "secondary": "#f5f5f5",
    "secondaryForeground": "#171717",
    "muted": "#f5f5f5",
    "mutedForeground": "#737373",
    "accent": "#f5f5f5",
    "accentForeground": "#171717",
    "destructive": "#e7000b",
    "destructiveForeground": "#ffffff",
    "border": "#e5e5e5",
    "input": "#e5e5e5",
    "ring": "#a1a1a1",
    "success": "#00a63e",
    "successForeground": "#ffffff",
    "warning": "#fe9a00",
    "warningForeground": "#0a0a0a",
    "info": "#155dfc",
    "infoForeground": "#ffffff",
    "series": [
      "#2a78d6",
      "#eb6834",
      "#1baf7a",
      "#eda100",
      "#e87ba4",
      "#008300",
      "#4a3aa7",
      "#e34948"
    ]
  },
  "dark": {
    "background": "#0a0a0a",
    "foreground": "#fafafa",
    "card": "#171717",
    "cardForeground": "#fafafa",
    "primary": "#e5e5e5",
    "primaryForeground": "#171717",
    "secondary": "#262626",
    "secondaryForeground": "#fafafa",
    "muted": "#262626",
    "mutedForeground": "#a1a1a1",
    "accent": "#262626",
    "accentForeground": "#fafafa",
    "destructive": "#ff6467",
    "destructiveForeground": "#0a0a0a",
    "border": "#ffffff1a",
    "input": "#ffffff26",
    "ring": "#737373",
    "success": "#00c950",
    "successForeground": "#0a0a0a",
    "warning": "#ffb900",
    "warningForeground": "#0a0a0a",
    "info": "#2b7fff",
    "infoForeground": "#0a0a0a",
    "series": [
      "#3987e5",
      "#d95926",
      "#199e70",
      "#c98500",
      "#d55181",
      "#008300",
      "#9085e9",
      "#e66767"
    ]
  },
  "space": {
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "6": 24,
    "8": 32,
    "12": 48
  },
  "radius": {
    "sm": 6,
    "md": 8,
    "lg": 10,
    "xl": 14,
    "full": 9999
  },
  "tap": 48
} as const;

export type ColorName = keyof typeof tokens.light;
